pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'echo "Hello World"'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh ''' 
             a=10
             b=67
             add = $((a + b))
         echo "Addition is : " ${add}
        '''
      }
    }
  }
}
